server:
  port: 8099
spring:
  application:
    name: meqaexcelreport

  datasource:
    url: jdbc:postgresql://localhost:5432/megacrm
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
